version: 2

build:
  os: ubuntu-22.04
  image: latest

sphinx:
  configuration: docs/conf.py

python:
  version: 3.11
  install:
    - method: pip
      path: .
    - method: pip
      packages:
        - sphinx>=8.1.3
        - sphinx-rtd-theme>=3.0.2
