language: python
dist: xenial  # required for Python >= 3.7
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - python setup.py install
script:
  - py.test
notifications:
  email:
    on_success: never
    on_failure: always
