#!/bin/sh
# Copyright 2018 Davide Alberani <da@erlug.linux.it>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# s3-reduce.sh: create smaller versions of .tsv.gz files

COUNT="100"

if [ "x$1" != "x" ] ; then
    pushd "$1"
fi

mkdir -p partials

for fname in *.tsv.gz
do
    zcat "${fname}" | head -${COUNT} | gzip -f - > "partials/${fname}"
done


if [ "x$1" != "x" ] ; then
    popd
fi
